### ISSUE TITLE
Bug: Login não valida e-mail no backend

### ISSUE THREAD

**Issue by felipe-dmb** [wgrfsantos/photel#13]
# Atual

É possível enviar uma string, sem ser um email válido, para o backend e esse processe na query SQL.

## Como reproduzir

Acesse a página de login e usando as ferramentas de desenvolvedor altere o elemento input de:
```html
<input type="email" name="email" class="form-control" placeholder="Email">
```

para:

```html
<input type="text" name="email" class="form-control" placeholder="Email">
```

Agora, digite qualquer texto, sem ser um e-mail, e envie.

# Resultado Esperado

O Backend deve validar a entrada de dados, e não realizar a consulta no banco sem que eles sejam válidos.
Sugestão: Usar a função `filter_input()` do PHP.

Arquivo: LoginController.php  -> index_action()

**Comment by claudioroch** [comment]
Validando o insert de e-mail com filter_input
